config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :articles, only: %i|index new create show edit update destroy|

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search', to: 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: true, length: {minimum: 4, maximum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: {case_sensitive: false},
                       length: {minimum: 3, maximum:25}
  VALID_EMAIL_REGEX_MINE = /\A\w+@\w+[.]{1}com{1}(\.br)?\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness:  {case_sensitive: false},
                    length: {maximum: 105},
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform this action'
      redirect_to login_path
    end
  end
  def fetch_categories
    @categories ||= Category.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :fetch_categories
  before_action :set_article, only: %i|show edit update destroy|
  before_action :require_user, except: [:show, :index]
  

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end
  
  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    msg = 'saved successfully'
    return redirect_to @article, notice: msg.to_s if @article.save
    render :new
  end

  def edit
  end

  def update
    msg = 'saved successfully'
    return redirect_to @article, notice: msg.to_s if (@article.user == current_user || current_user.admin? )&& @article.update(article_params)
    render :edit
  end

  def destroy
    @articles = Article.all
    @article.delete if @article.user == current_user || current_user.admin?
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :fetch_categories
  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @category = Category.new()
  end

  def create
    @category = Category.new(category_params)
    return redirect_to @category, notice: 'Category was successfully created' if @category.save
    render :new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category successfully updated'
      redirect_to @category
    else
      render :edit
    end
    
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:alert] = 'Only admins allowed to do that...'
      redirect_to categories_path 
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :fetch_categories
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

  def search
    if !params[:search].empty? && @search_text = params[:search]
      @articles = Article
                    .where("lower(title) LIKE ?",
                           "%#{@search_text.downcase}%")
                      .or(Article
                            .where("lower(description) LIKE ?",
                                  "%#{@search_text.downcase}%"))
                              .paginate(page: params[:page], per_page: 5)
                              .order('created_at DESC')
    else
      @articles = []
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :fetch_categories
  def  new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Hello #{user.username}, nice to see you again."
      redirect_to user

    else
      flash.now[:alert] = "Ops, there's something wrong"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_categories
  before_action :set_user, only: [:show]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :set_safe_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user =User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      msg = "You have successfully signed up #{@user.username}".to_sym
      flash[:notice] = msg
      session[:user_id] = @user.id
      redirect_to @user
    else
    render :new
    end
  end

  def edit
  end

  def update
    msg = "You have successfully updated your data".to_sym
    return redirect_to @user, notice: msg if (current_user == @user || current_user.admin?) && @user.update(user_params)

    render :edit
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def destroy
    session[:user_id] = nil if !current_user.admin?
    flash[:notice] = 'Account and all posts susccessfully deleted'
    return redirect_to root_path if @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user =User.find(params[:id])
  end
  def set_safe_user
    return set_user if current_user.admin?
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    hash = Digest::MD5.hexdigest(user.email)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag image_src, alt: user.username, class:"rounded shadow mx-auto d-block"
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5">
          <div class="card-header font-italic">
            by <%=link_to article.user.username, user_path(article.user)%>
          </div>
          <div class="card-body">
            

            <h5 class="card-title"><%= link_to  article.title, article_path(article),class: 'text-success' %></h5>
            <p class="card-text"><%= article.description.truncate_words(10) %></p>
            <%= link_to  "View", article_path(article), class:"btn btn-outline-success" %>
            
            <% if article.user == current_user || (current_user && current_user.admin?) %>
              <%= link_to  "Edit", edit_article_path(article), class:"btn btn-outline-primary" %>
              <%= link_to  "Delete", article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-outline-danger" %>
            <% end %>   
          </div>
          <div class="card-footer text-muted">
            <% unless article.categories.empty?%>
              <small>Categories:
                <% article.categories.each do |category|%>
                  <%= link_to  category.name, category_path(category) %>
                <% end %>
              </small>
              <hr>
            <% end %>
            <small>
              Created <%= time_ago_in_words(article.created_at) %> ago, 
              Modified: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @article %>

  <div class="row justify-content-center">
    <div class="col-10">

      <%= form_with model: @article, local: true, class: 'shadow p-4 mb-3 bg-info' do |f| %>
        <div class="form-group row">
            <%= f.label :title , 'Title:', class: 'col-3 col-form-label text-white'%>
            <%= f.text_field :title, class:'col-8 form-cotrol shadow rounded', placeholder: "Title of article", autofocus: true %>
        </div>

        <div class="form-group row">
            <%= f.label :description, 'Desc:', class: 'col-3 col-form-label text-white' %>
            <%= f.text_area :description, rows: 10, class: "col-8 form-control shadow rounded", placeholder: "Description of article" %>
        </div>

        <!-- CHECKBOX -->
        <div class="form-group row justify-content-center">
            <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cb| %>
              <% cb.label(class: 'checkbox-inline input_checkbox') {cb.check_box(class: 'checkbox')+ cb.text}%>
            <% end %>
        </div>


        <div class="form-group row justify-content-center">
            <%= f.submit class: 'btn btn-outline-light btn-lg' %>
        </div>
      <% end %>
    
    </div>

    <div class="mb-3">
      <%= link_to "| Cancel request and return to articles listing |", articles_path, class: 'text-info' %>
    </div>
  </div>

</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render  "article" %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>


<div class="container">
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5">
          <div class="card-header font-italic">
            by <%= @article.user.username if @article.user%>
            <%= link_to gravatar_for(@article.user, size: 50), user_path(@article.user)%>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if @article.user == current_user %>
              <%= link_to  "Edit", edit_article_path(@article), class:"btn btn-outline-primary" %>
              <%= link_to  "Delete", article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-outline-danger" %>
            <% end %>     
          </div>
          <div class="card-footer text-muted">
            <small>
            Created <%= time_ago_in_words(@article.created_at) %> ago, 
            Modified: <%= time_ago_in_words(@article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/categories/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @category %>
  <div class="row justify-content-center">
    <div class="col-10">

      <%= form_with model: @category, local: true, class: 'shadow p-4 mb-3 bg-info' do |f| %>
        <div class="form-group row">
            <%= f.label :name , 'Category Name:', class: 'col-3 col-form-label text-white'%>
            <%= f.text_field :name, class:'col-8 form-cotrol shadow rounded', placeholder: "Enter name for category", autofocus: true %>
        </div>

        <div class="form-group row justify-content-center">
            <%= f.submit(@category.new_record? ? 'Create' : 'Update', class: 'btn btn-outline-light btn-lg')%>
        </div>
      <% end %>
    
    </div>

    <div class="mb-3">
      <%= link_to "| Cancel request and return to articles listing |", articles_path, class: 'text-info' %>
    </div>
  </div>

</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit a category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5">
          
          <div class="card-body">
            
            <h5 class="card-title">
              <%= link_to  category.name, category_path(category),class: 'text-success' %>
            </h5>
            <small>
              <%= pluralize(category.articles.count, 'article')%>
            </small>
          </div>
          <div class="card-footer text-muted">
            <small>
            Created <%= time_ago_in_words(category.created_at) %> ago, 
            Modified: <%= time_ago_in_words(category.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <p class="text-center mt-4">
    <%= link_to  'Edit category name' , edit_category_path(@category), class: 'btn btn-outline-light btn-lg', style: 'font-size: 1em;' %>
  </p>
<% end %>

<% if @articles.empty? %>
  <h3 class="text-center mt-4">
    Ops... there still no article for this category
  </h3>
<% end %>


<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render  "articles/article" %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert <%= (name=='notice')? "alert-success": "alert-danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to  "Home", root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to  "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to articles_path, class:'dropdown-item' do %>
            View articles 
          <% end %>

          <% if logged_in? %>
            <%= link_to new_article_path, class:'dropdown-item' do %>
              Create new article
            <% end %>
          <% end %>
          <!--div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div-->
        </div>
      </li>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">

          <%= link_to  "Categories", '#', class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to  "Add new categorie", new_category_path, class: 'dropdown-item' %>
          <% end %>
          <%= link_to  "All Categories", categories_path, class: 'dropdown-item' %>
            <% @categories.sort_by{|item| item.name }.each do |category| %>
              <%= link_to  category.name, category_path(category), class: 'dropdown-item' %>
            <% end %>
          </div>

        </li>
      </ul>

    </ul>



    <form class="form-inline my-2 my-lg-0">

      <% if logged_in? %>
        <%=link_to gravatar_for(current_user , size: 50), user_path(current_user) %>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">

            <%= link_to  "#{(current_user.admin?)? 'ADM - ': ''}#{current_user.username}", '#', class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to  "Edit your profile", edit_user_path(current_user), class: 'dropdown-item' %>
              <%= link_to  "Delete your profile", user_path(current_user), method: :delete, class: 'dropdown-item text-danger', data: {confirm: 'Are you sure you want to delete your user and all your posts?'} %>
            </div>

          </li>
        </ul>

      <% else %>
        <%= link_to  'Sign up', signup_path, class: "nav-link" %>
      <% end %>

      <% if logged_in? %>
        <%= link_to  "Log out", logout_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to  "Log in", login_path, class: 'nav-link' %>
      <% end %>

    </form>
    <%= form_with(url: '/search', method: :get, class: 'form-inline',local: true) do |f| %>
      <%= f.text_field :search, class: "mr-sm-2 form-control", type: "text", placeholder: "Search", aria: {label: "Search"} %>

      <%= f.submit 'Busca', class:"btn btn-info my-2 my-sm-0"%>

    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

    <%= render partial: 'layouts/navigation' %>
    <div id="page-content">
      <%= render partial: 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render partial: 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to  "Home listing", root_path %> |
<%= link_to  "Articles listing", articles_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha blog</h1>
    <p class="lead">Simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>With bootstrap.</p>
    <% unless session[:user_id] %>
      <a class="btn btn-success btn-lg" href="<%= signup_path%>" role="button">Sign up</a>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
<% unless @articles.empty?%>
    <h1 class="text-center mt-4">Listing articles with: '<%= params[:search]%>'</h1>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render  "articles/article" %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>
<% else %>
     <h1 class="text-center mt-4">Ops! we couldn't find anything T.T</h1>
<% end %>

app/views/shared/_errors.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <% if obj.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %> from being saved:</h4>
        <ul>
          <% obj.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @user %>
  <div class="row justify-content-center">
    <div class="col-10">

      <%= form_with model: @user, local: true, class: 'shadow p-4 mb-3 bg-info' do |f| %>
        <div class="form-group row">
            <%= f.label :username , 'Name:', class: 'col-3 col-form-label text-white'%>
            <%= f.text_field :username, class:'col-8 form-cotrol shadow rounded', placeholder: "Enter your name", autofocus: true %>
        </div>

        <div class="form-group row">
            <%= f.label :email , 'Email:', class: 'col-3 col-form-label text-white'%>
            <%= f.email_field :email, class:'col-8 form-cotrol shadow rounded', placeholder: "Enter your email", autofocus: true %>
        </div>

        <div class="form-group row">
            <%= f.label :password, 'Password:', class: 'col-3 col-form-label text-white' %>
            <%= f.password_field :password, class: "col-8 form-control shadow rounded", placeholder: "Choose a password", value:''%>
        </div>

        <div class="form-group row justify-content-center">
            <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: 'btn btn-outline-light btn-lg')%>
        </div>
      <% end %>
    
    </div>

    <div class="mb-3">
      <%= link_to "| Cancel request and return to articles listing |", articles_path, class: 'text-info' %>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit</h1>
<%= render partial: 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Bloggers</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5">
          <div class="card-header font-italic">
            <%= link_to user.username, user%>
          </div>
          <div class="card-body">
            

            <h5 class="card-title">
              <%= link_to  gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize user.articles.count, 'article' %></p>
            <%= link_to  "View profile", user, class:"btn btn-outline-success" %>
            <%if current_user == user%>
              <%= link_to  "Edit profile", edit_user_path(user), class:"btn btn-outline-primary" %>                
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>
            Joined <%= time_ago_in_words(user.created_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup</h1>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && current_user == @user%>
  <div class="text-center mt-4">
    <%= link_to  "Edit your profile", edit_user_path(@user), class: 'btn btn-outline-info' %>
  </div>
<% end %>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to  "Delete this profile", user_path(@user), method: :delete, class: 'btn btn-outline-danger', data: {confirm: 'Are you sure you want to delete this user and all your posts?'} %>
  </div>
<% end %>


<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render  "articles/article" %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>